// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WordStudy.Data;

namespace WordStudy.Data.Migrations
{
    [DbContext(typeof(EWSDbContext))]
    [Migration("20181205142354_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("WordStudy.Data.Model.Usr", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<string>("SurName");

                    b.Property<string>("UserName");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WordStudy.Data.Model.Word", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AddType");

                    b.Property<string>("Body");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Mean");

                    b.Property<int?>("WrdListID");

                    b.HasKey("ID");

                    b.HasIndex("WrdListID");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("WordStudy.Data.Model.WordOfList", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ListID");

                    b.Property<int>("WordID");

                    b.Property<int?>("WrdListID");

                    b.HasKey("ID");

                    b.HasIndex("WordID");

                    b.HasIndex("WrdListID");

                    b.ToTable("WordOfLists");
                });

            modelBuilder.Entity("WordStudy.Data.Model.WrdList", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ListName");

                    b.Property<int>("UsrID");

                    b.HasKey("ID");

                    b.ToTable("WrdLists");
                });

            modelBuilder.Entity("WordStudy.Data.Model.Word", b =>
                {
                    b.HasOne("WordStudy.Data.Model.WrdList")
                        .WithMany("Words")
                        .HasForeignKey("WrdListID");
                });

            modelBuilder.Entity("WordStudy.Data.Model.WordOfList", b =>
                {
                    b.HasOne("WordStudy.Data.Model.Word", "Word")
                        .WithMany()
                        .HasForeignKey("WordID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WordStudy.Data.Model.WrdList", "WrdList")
                        .WithMany()
                        .HasForeignKey("WrdListID");
                });
#pragma warning restore 612, 618
        }
    }
}
